name: IO App Cypress

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  Cypress:
    uses: vtex/action-io-app-cypress/.github/workflows/cypress.yml@v1
    with:
      accounts: '["vtexgame1"]'
      parallel: true
      containers: 30
    secrets:
      app-key: ${{ secrets.APP_KEY }}
      app-token: ${{ secrets.APP_TOKEN }}
      record-key: ${{ secrets.RECORD_KEY }}
